// Plantbase — szintetikus növény-katalógus (~30 tétel) a seedhez.
// Valós fajnevek, reális attribútumok a stack.md értékkészletei szerint.
// A mezőnevek a Prisma Product modell camelCase nevei (createMany input).
//
// Szándékosan vegyes az adat, hogy a lekérdezések értelmesek legyenek:
// - van akciós (salePrice != null) és teljes áras tétel,
// - van raktáron lévő (stock > 0) és kifogyott (stock = 0),
// - lefedi az összes kategóriát, fény- és öntözés-szintet, mindhárom nehézséget,
// - vegyes pet_safe / kid_safe / air_purifying.

export interface PlantSeed {
  name: string;
  latinName: string;
  category: string; // szobanövény / kerti / pozsgás / kaktusz / fűszer / fa-cserje / lógó / virágzó
  location: string; // beltéri / kültéri / mindkettő
  price: number; // HUF
  salePrice: number | null; // akciós ár, null ha nincs akció
  stock: number;
  light: string; // árnyék / alacsony / közepes / erős / direkt nap
  watering: string; // ritka / közepes / gyakori / állandóan nedves
  difficulty: string; // kezdő / haladó / profi
  currentHeightCm: number;
  maxHeightCm: number;
  currentPotCm: number;
  petSafe: boolean;
  kidSafe: boolean;
  airPurifying: boolean;
  rating: number; // 0-5
  reviewsCount: number;
  description: string;
}

export const plants: PlantSeed[] = [
  {
    name: 'Vitorlavirág',
    latinName: 'Spathiphyllum wallisii',
    category: 'szobanövény',
    location: 'beltéri',
    price: 4990,
    salePrice: 3990,
    stock: 24,
    light: 'alacsony',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 40,
    maxHeightCm: 65,
    currentPotCm: 14,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.6,
    reviewsCount: 212,
    description:
      'Elegáns, fehér vitorlájú virágzó szobanövény, amely alacsony fényben is jól bírja. Kiváló légtisztító, de háziállatra és gyerekre mérgező lehet.',
  },
  {
    name: 'Aranypálma',
    latinName: 'Dypsis lutescens',
    category: 'szobanövény',
    location: 'beltéri',
    price: 8990,
    salePrice: null,
    stock: 12,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 90,
    maxHeightCm: 200,
    currentPotCm: 21,
    petSafe: true,
    kidSafe: true,
    airPurifying: true,
    rating: 4.5,
    reviewsCount: 143,
    description:
      'Dús, ívelő leveleivel trópusi hangulatot ad. Háziállat-barát és légtisztító, világos helyet kedvel közvetlen tűző nap nélkül.',
  },
  {
    name: 'Kentia pálma',
    latinName: 'Howea forsteriana',
    category: 'szobanövény',
    location: 'beltéri',
    price: 15990,
    salePrice: 13990,
    stock: 6,
    light: 'alacsony',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 110,
    maxHeightCm: 250,
    currentPotCm: 24,
    petSafe: true,
    kidSafe: true,
    airPurifying: true,
    rating: 4.8,
    reviewsCount: 98,
    description:
      'Robusztus, előkelő pálma, amely félárnyékot is tűr. Háziállatra veszélytelen, ideális nagyobb nappalikba.',
  },
  {
    name: 'Anyósnyelv',
    latinName: 'Dracaena trifasciata',
    category: 'szobanövény',
    location: 'beltéri',
    price: 3490,
    salePrice: null,
    stock: 40,
    light: 'alacsony',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 45,
    maxHeightCm: 90,
    currentPotCm: 13,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.7,
    reviewsCount: 305,
    description:
      'Szinte elpusztíthatatlan, kevés fénnyel és ritka öntözéssel is boldogul. Kiváló kezdőknek, de háziállatra mérgező.',
  },
  {
    name: 'Zamiokulkász',
    latinName: 'Zamioculcas zamiifolia',
    category: 'szobanövény',
    location: 'beltéri',
    price: 5490,
    salePrice: 4490,
    stock: 28,
    light: 'alacsony',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 50,
    maxHeightCm: 80,
    currentPotCm: 15,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.6,
    reviewsCount: 187,
    description:
      'Fényes, viaszos levelű, rendkívül strapabíró növény. Sötétebb sarkokba is tökéletes, de nedve bőrirritáló és állatra mérgező.',
  },
  {
    name: 'Gumifa',
    latinName: 'Ficus elastica',
    category: 'szobanövény',
    location: 'beltéri',
    price: 6490,
    salePrice: null,
    stock: 18,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 70,
    maxHeightCm: 200,
    currentPotCm: 19,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.4,
    reviewsCount: 156,
    description:
      'Nagy, bőrszerű, sötétzöld levelekkel. Látványos szoladarab világos helyen; tejnedve háziállatra és gyerekre irritáló.',
  },
  {
    name: 'Lyukaslevél',
    latinName: 'Monstera deliciosa',
    category: 'szobanövény',
    location: 'beltéri',
    price: 7990,
    salePrice: 6490,
    stock: 22,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 60,
    maxHeightCm: 300,
    currentPotCm: 19,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.7,
    reviewsCount: 421,
    description:
      'Ikonikus, hasított levelű trópusi kúszónövény. Divatos és mutatós, de a levelek háziállatra mérgezőek.',
  },
  {
    name: 'Fikusz benjámin',
    latinName: 'Ficus benjamina',
    category: 'fa-cserje',
    location: 'beltéri',
    price: 6990,
    salePrice: null,
    stock: 0,
    light: 'erős',
    watering: 'közepes',
    difficulty: 'haladó',
    currentHeightCm: 100,
    maxHeightCm: 250,
    currentPotCm: 21,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.2,
    reviewsCount: 134,
    description:
      'Klasszikus szobafa apró, csillogó levelekkel. Érzékeny a helyváltoztatásra (lombhullás), állandó, világos helyet igényel.',
  },
  {
    name: 'Szobafenyő',
    latinName: 'Araucaria heterophylla',
    category: 'fa-cserje',
    location: 'beltéri',
    price: 5990,
    salePrice: null,
    stock: 9,
    light: 'erős',
    watering: 'közepes',
    difficulty: 'haladó',
    currentHeightCm: 80,
    maxHeightCm: 200,
    currentPotCm: 19,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.1,
    reviewsCount: 76,
    description:
      'Örökzöld, karácsonyfa-hangulatú szobafa. Párás, világos helyet szeret; háziállatra biztonságos.',
  },
  {
    name: 'Aranyinda',
    latinName: 'Epipremnum aureum',
    category: 'lógó',
    location: 'beltéri',
    price: 2990,
    salePrice: 2290,
    stock: 55,
    light: 'alacsony',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 20,
    maxHeightCm: 180,
    currentPotCm: 12,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.8,
    reviewsCount: 512,
    description:
      'Rendkívül hálás, csüngő vagy felfuttatható inda. Kevés fénnyel is nő, de a levelek állatra mérgezőek.',
  },
  {
    name: 'Szíves filodendron',
    latinName: 'Philodendron hederaceum',
    category: 'lógó',
    location: 'beltéri',
    price: 3290,
    salePrice: null,
    stock: 33,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 25,
    maxHeightCm: 150,
    currentPotCm: 12,
    petSafe: false,
    kidSafe: false,
    airPurifying: true,
    rating: 4.6,
    reviewsCount: 233,
    description:
      'Szív alakú levelű, gyorsan növő csüngő növény. Polcra, akasztóba ideális; nedve irritáló, állatra mérgező.',
  },
  {
    name: 'Csokrosinda',
    latinName: 'Chlorophytum comosum',
    category: 'lógó',
    location: 'beltéri',
    price: 2490,
    salePrice: null,
    stock: 47,
    light: 'alacsony',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 25,
    maxHeightCm: 40,
    currentPotCm: 12,
    petSafe: true,
    kidSafe: true,
    airPurifying: true,
    rating: 4.7,
    reviewsCount: 289,
    description:
      'Csíkos levelű, sarjakat hajtó klasszikus. Háziállat-barát, gyerekbiztos és jó légtisztító — tökéletes első növény.',
  },
  {
    name: 'Kroton',
    latinName: 'Codiaeum variegatum',
    category: 'szobanövény',
    location: 'beltéri',
    price: 4290,
    salePrice: null,
    stock: 0,
    light: 'erős',
    watering: 'közepes',
    difficulty: 'haladó',
    currentHeightCm: 35,
    maxHeightCm: 100,
    currentPotCm: 15,
    petSafe: false,
    kidSafe: false,
    airPurifying: false,
    rating: 4.0,
    reviewsCount: 64,
    description:
      'Tűzpiros-sárga-zöld tarka lombozat. Sok fényt kíván a színekhez; nedve mérgező, kezdőknek nehéz.',
  },
  {
    name: 'Pénzfa',
    latinName: 'Crassula ovata',
    category: 'pozsgás',
    location: 'beltéri',
    price: 3790,
    salePrice: 2990,
    stock: 30,
    light: 'erős',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 25,
    maxHeightCm: 90,
    currentPotCm: 13,
    petSafe: false,
    kidSafe: true,
    airPurifying: false,
    rating: 4.5,
    reviewsCount: 178,
    description:
      'Vaskos, fás szárú pozsgás, a „szerencsefa". Napos ablakban és ritka öntözéssel él a legjobban; macskára enyhén mérgező.',
  },
  {
    name: 'Aloe vera',
    latinName: 'Aloe vera',
    category: 'pozsgás',
    location: 'mindkettő',
    price: 2790,
    salePrice: null,
    stock: 38,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 30,
    maxHeightCm: 60,
    currentPotCm: 14,
    petSafe: false,
    kidSafe: true,
    airPurifying: true,
    rating: 4.6,
    reviewsCount: 254,
    description:
      'Gyógyhatású gél a leveleiben; napfényt és kevés vizet igényel. Praktikus és dekoratív, de háziállatra mérgező.',
  },
  {
    name: 'Kövirózsa',
    latinName: 'Echeveria elegans',
    category: 'pozsgás',
    location: 'mindkettő',
    price: 1690,
    salePrice: null,
    stock: 64,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 8,
    maxHeightCm: 15,
    currentPotCm: 9,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.4,
    reviewsCount: 141,
    description:
      'Rózsaszerűen rendeződő, pasztell pozsgás. Apró, olcsó, háziállat-barát — ablakpárkányra és csokorba is ideális.',
  },
  {
    name: 'Zebrapozsgás',
    latinName: 'Haworthiopsis fasciata',
    category: 'pozsgás',
    location: 'beltéri',
    price: 1990,
    salePrice: 1490,
    stock: 52,
    light: 'közepes',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 10,
    maxHeightCm: 20,
    currentPotCm: 9,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.5,
    reviewsCount: 119,
    description:
      'Fehér csíkos, kompakt pozsgás, amely közepes fényt is elvisel. Háziállat-barát, kisméretű, gondozásmentes.',
  },
  {
    name: 'Aranylabda kaktusz',
    latinName: 'Echinocactus grusonii',
    category: 'kaktusz',
    location: 'beltéri',
    price: 4990,
    salePrice: null,
    stock: 15,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'haladó',
    currentHeightCm: 18,
    maxHeightCm: 80,
    currentPotCm: 15,
    petSafe: true,
    kidSafe: false,
    airPurifying: false,
    rating: 4.3,
    reviewsCount: 87,
    description:
      'Gömb alakú, aranytüskés kaktusz. Sok napfényt és nagyon kevés vizet kíván; tüskéi miatt gyerek közelébe nem való.',
  },
  {
    name: 'Karácsonyi kaktusz',
    latinName: 'Schlumbergera truncata',
    category: 'kaktusz',
    location: 'beltéri',
    price: 3290,
    salePrice: 2590,
    stock: 26,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 20,
    maxHeightCm: 40,
    currentPotCm: 13,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.6,
    reviewsCount: 163,
    description:
      'Télen, ünnepek táján nyíló, csüngő szárú kaktusz. Háziállatra veszélytelen, hálásan virágzik közepes fényben.',
  },
  {
    name: 'Bazsalikom',
    latinName: 'Ocimum basilicum',
    category: 'fűszer',
    location: 'mindkettő',
    price: 990,
    salePrice: null,
    stock: 80,
    light: 'erős',
    watering: 'gyakori',
    difficulty: 'kezdő',
    currentHeightCm: 20,
    maxHeightCm: 45,
    currentPotCm: 12,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.3,
    reviewsCount: 201,
    description:
      'Illatos konyhai fűszer, amely napos helyen és rendszeres öntözéssel dúsan hajt. Ehető, háziállat-barát.',
  },
  {
    name: 'Rozmaring',
    latinName: 'Salvia rosmarinus',
    category: 'fűszer',
    location: 'mindkettő',
    price: 1490,
    salePrice: null,
    stock: 44,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'kezdő',
    currentHeightCm: 25,
    maxHeightCm: 120,
    currentPotCm: 13,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.4,
    reviewsCount: 158,
    description:
      'Örökzöld, fás szárú konyhai fűszer intenzív illattal. Szereti a napot és a száraz talajt; állatra és gyerekre biztonságos.',
  },
  {
    name: 'Fodormenta',
    latinName: 'Mentha spicata',
    category: 'fűszer',
    location: 'mindkettő',
    price: 990,
    salePrice: 790,
    stock: 60,
    light: 'közepes',
    watering: 'gyakori',
    difficulty: 'kezdő',
    currentHeightCm: 18,
    maxHeightCm: 60,
    currentPotCm: 12,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.2,
    reviewsCount: 132,
    description:
      'Gyorsan terjedő, üdítő illatú fűszernövény. Nedves talajt és félárnyékot is elvisel; teához, koktélhoz ideális.',
  },
  {
    name: 'Levendula',
    latinName: 'Lavandula angustifolia',
    category: 'virágzó',
    location: 'kültéri',
    price: 2290,
    salePrice: null,
    stock: 35,
    light: 'direkt nap',
    watering: 'ritka',
    difficulty: 'haladó',
    currentHeightCm: 30,
    maxHeightCm: 80,
    currentPotCm: 15,
    petSafe: false,
    kidSafe: true,
    airPurifying: false,
    rating: 4.7,
    reviewsCount: 276,
    description:
      'Illatos, lila virágfüzérek; méhbarát kerti dísz. Tűző napot és jó vízelvezetést kíván; nagyobb mennyiségben állatra mérgező.',
  },
  {
    name: 'Japán juhar',
    latinName: 'Acer palmatum',
    category: 'fa-cserje',
    location: 'kültéri',
    price: 12990,
    salePrice: 9990,
    stock: 8,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'profi',
    currentHeightCm: 70,
    maxHeightCm: 400,
    currentPotCm: 24,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.8,
    reviewsCount: 92,
    description:
      'Finoman szeldelt levelű, ősszel tűzpirosba forduló díszfa. Félárnyékot és széltől védett helyet szeret; háziállatra veszélytelen.',
  },
  {
    name: 'Kerti hortenzia',
    latinName: 'Hydrangea macrophylla',
    category: 'virágzó',
    location: 'kültéri',
    price: 3990,
    salePrice: null,
    stock: 0,
    light: 'közepes',
    watering: 'gyakori',
    difficulty: 'haladó',
    currentHeightCm: 40,
    maxHeightCm: 150,
    currentPotCm: 17,
    petSafe: false,
    kidSafe: false,
    airPurifying: false,
    rating: 4.5,
    reviewsCount: 187,
    description:
      'Nagy, gömbölyű virágzatú kerti cserje, a talaj kémhatásától függő színnel. Sok vizet és félárnyékot kíván; háziállatra mérgező.',
  },
  {
    name: 'Muskátli',
    latinName: 'Pelargonium zonale',
    category: 'virágzó',
    location: 'mindkettő',
    price: 1290,
    salePrice: null,
    stock: 72,
    light: 'erős',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 20,
    maxHeightCm: 50,
    currentPotCm: 12,
    petSafe: false,
    kidSafe: true,
    airPurifying: false,
    rating: 4.3,
    reviewsCount: 214,
    description:
      'Klasszikus balkonvirág, egész nyáron folyamatosan nyílik. Napos helyet és mérsékelt öntözést szeret; háziállatra enyhén mérgező.',
  },
  {
    name: 'Lepkeorchidea',
    latinName: 'Phalaenopsis amabilis',
    category: 'virágzó',
    location: 'beltéri',
    price: 4490,
    salePrice: 3490,
    stock: 29,
    light: 'közepes',
    watering: 'ritka',
    difficulty: 'haladó',
    currentHeightCm: 45,
    maxHeightCm: 70,
    currentPotCm: 12,
    petSafe: true,
    kidSafe: true,
    airPurifying: false,
    rating: 4.6,
    reviewsCount: 341,
    description:
      'Hetekig nyíló, elegáns szobai orchidea. Szűrt fényt és ritka öntözést igényel; háziállatra és gyerekre biztonságos.',
  },
  {
    name: 'Királybegónia',
    latinName: 'Begonia rex',
    category: 'virágzó',
    location: 'beltéri',
    price: 3690,
    salePrice: null,
    stock: 21,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'haladó',
    currentHeightCm: 25,
    maxHeightCm: 45,
    currentPotCm: 14,
    petSafe: false,
    kidSafe: false,
    airPurifying: false,
    rating: 4.2,
    reviewsCount: 88,
    description:
      'Feltűnő, fémes-mintás levelekért tartott begónia. Párás levegőt és egyenletes nedvességet kíván; háziállatra mérgező.',
  },
  {
    name: 'Buxus',
    latinName: 'Buxus sempervirens',
    category: 'kerti',
    location: 'kültéri',
    price: 2990,
    salePrice: 2390,
    stock: 40,
    light: 'közepes',
    watering: 'közepes',
    difficulty: 'kezdő',
    currentHeightCm: 30,
    maxHeightCm: 300,
    currentPotCm: 15,
    petSafe: false,
    kidSafe: false,
    airPurifying: false,
    rating: 4.1,
    reviewsCount: 103,
    description:
      'Sűrű, örökzöld, jól nyírható kerti sövénycserje. Formára metszhető; levele és termése állatra és gyerekre mérgező.',
  },
  {
    name: 'Pávalevél',
    latinName: 'Goeppertia makoyana',
    category: 'szobanövény',
    location: 'beltéri',
    price: 4790,
    salePrice: null,
    stock: 17,
    light: 'alacsony',
    watering: 'gyakori',
    difficulty: 'profi',
    currentHeightCm: 35,
    maxHeightCm: 60,
    currentPotCm: 14,
    petSafe: true,
    kidSafe: true,
    airPurifying: true,
    rating: 4.3,
    reviewsCount: 126,
    description:
      'Dekoratív, pávatoll-mintás levelekkel, amelyek este felkunkorodnak. Párás levegőt és egyenletes nedvességet kíván; háziállat-barát, de igényes.',
  },
];
